'use client';

import { useEffect, useState } from 'react';
import {
  Building2,
  Check,
  CheckCircle2,
  Copy,
  Cpu,
  Key,
  Lock,
  Phone,
  Save,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
} from 'lucide-react';
import { Header } from '@/components/Header';
import { Sidebar } from '@/components/Sidebar';
import {
  activateLicense,
  fetchBranding,
  fetchLicenseStatus,
  updateBranding,
  type AgencyBranding,
  type LicenseStatus,
} from '@/lib/api';

export default function SettingsPage() {
  const [license, setLicense] = useState<LicenseStatus | null>(null);
  const [branding, setBranding] = useState<AgencyBranding>({
    agency_name: 'SRA Software Solutions',
    tagline: 'Find. Verify. Connect. • Tamil Nadu Edition',
    support_phone: '+91 98400 12345',
    support_email: 'support@srasoftware.com',
    currency: 'INR',
    lead_export_watermark: 'Generated by SRA Lead Finder',
  });

  const [inputKey, setInputKey] = useState('');
  const [hwidCopied, setHwidCopied] = useState(false);
  const [activating, setActivating] = useState(false);
  const [savingBranding, setSavingBranding] = useState(false);
  const [activationMsg, setActivationMsg] = useState<{ success: boolean; text: string } | null>(null);
  const [brandingSaved, setBrandingSaved] = useState(false);

  useEffect(() => {
    fetchLicenseStatus()
      .then(setLicense)
      .catch((e) => console.error('Failed to load license:', e));
    fetchBranding()
      .then(setBranding)
      .catch((e) => console.error('Failed to load branding:', e));
  }, []);

  const handleCopyHwid = () => {
    if (license?.hardware_id) {
      navigator.clipboard.writeText(license.hardware_id);
      setHwidCopied(true);
      setTimeout(() => setHwidCopied(false), 2000);
    }
  };

  const handleActivate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputKey.trim()) return;

    setActivating(true);
    setActivationMsg(null);
    try {
      const res = await activateLicense(inputKey.trim());
      setActivationMsg({ success: true, text: res.message || 'Software activated successfully!' });
      // Refresh status
      const updated = await fetchLicenseStatus();
      setLicense(updated);
      setInputKey('');
    } catch (err: any) {
      setActivationMsg({
        success: false,
        text: err?.message || 'Invalid license key for this Hardware ID. Please verify and try again.',
      });
    } finally {
      setActivating(false);
    }
  };

  const handleSaveBranding = async (e: React.FormEvent) => {
    e.preventDefault();
    setSavingBranding(true);
    try {
      await updateBranding(branding);
      setBrandingSaved(true);
      setTimeout(() => setBrandingSaved(false), 2500);
    } catch (e) {
      console.error('Failed to save branding:', e);
    } finally {
      setSavingBranding(false);
    }
  };

  const isActivated = Boolean(license?.is_activated);

  return (
    <div className="flex min-h-screen bg-[#f8fafc]">
      <Sidebar />
      <main className="min-w-0 flex-1 px-5 py-6 sm:px-8 lg:px-12">
        <Header
          title="Software Settings & License"
          subtitle="Machine activation, agency white-labeling, and data scraper configurations"
        />

        <div className="max-w-4xl space-y-6">
          {/* 1. SOFTWARE LICENSE & MACHINE ID SECTION */}
          <section className="rounded-2xl border border-line bg-white p-6 shadow-xs space-y-4">
            <div className="flex items-center justify-between border-b border-line pb-4">
              <div className="flex items-center gap-2.5">
                <div
                  className={`flex h-10 w-10 items-center justify-center rounded-xl text-white shadow-md ${
                    isActivated ? 'bg-emerald-600 shadow-emerald-600/20' : 'bg-blue shadow-blue/20'
                  }`}
                >
                  {isActivated ? <ShieldCheck size={22} /> : <Shield size={22} />}
                </div>
                <div>
                  <h3 className="text-base font-bold text-ink">Software License & Machine Activation</h3>
                  <p className="text-xs text-muted">
                    Hardware-locked commercial protection. Validated exclusively for this computer.
                  </p>
                </div>
              </div>

              <span
                className={`rounded-full px-3 py-1 text-xs font-black uppercase tracking-wider ${
                  isActivated
                    ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                    : 'bg-amber-100 text-amber-800 border border-amber-300'
                }`}
              >
                {isActivated ? `${license?.license_type || 'LIFETIME'} ACTIVATED` : 'EVALUATION TRIAL'}
              </span>
            </div>

            {/* Hardware ID Display Box */}
            <div className="rounded-xl border border-line bg-slate-50 p-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block">
                    Your Machine Hardware ID (HWID)
                  </span>
                  <div className="flex items-center gap-2 mt-1">
                    <Cpu size={16} className="text-blue" />
                    <code className="text-sm font-black tracking-wide text-slate-900 bg-white px-2.5 py-1 rounded-lg border border-line shadow-2xs font-mono">
                      {license?.hardware_id || 'Detecting Hardware...'}
                    </code>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleCopyHwid}
                  className="inline-flex items-center gap-1.5 rounded-xl border border-line bg-white px-3.5 py-2 text-xs font-bold text-slate-700 hover:bg-slate-100 transition shadow-2xs"
                >
                  {hwidCopied ? <Check size={14} className="text-emerald-600" /> : <Copy size={14} />}
                  <span>{hwidCopied ? 'HWID Copied!' : 'Copy Hardware ID'}</span>
                </button>
              </div>
              <p className="text-[11px] text-slate-500 mt-2">
                Share this Hardware ID with the seller to obtain your official Lifetime Activation Key.
              </p>
            </div>

            {/* Activation Form */}
            {!isActivated ? (
              <form onSubmit={handleActivate} className="space-y-3 pt-1">
                <label className="text-xs font-bold uppercase tracking-wider text-slate-700 block">
                  Enter License Activation Key:
                </label>
                <div className="flex gap-2">
                  <div className="relative flex-1">
                    <Key size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" />
                    <input
                      type="text"
                      placeholder="e.g. LIC-XXXX-XXXX-XXXX-XXXX"
                      value={inputKey}
                      onChange={(e) => setInputKey(e.target.value)}
                      className="w-full rounded-xl border border-line bg-white py-2.5 pl-9 pr-3 text-xs font-mono font-bold uppercase tracking-wider text-slate-900 outline-none focus:border-blue shadow-inner"
                    />
                  </div>
                  <button
                    type="submit"
                    disabled={activating || !inputKey.trim()}
                    className="inline-flex items-center gap-2 rounded-xl bg-blue px-5 py-2.5 text-xs font-bold text-white hover:bg-blue/90 transition shadow-md shadow-blue/20 disabled:opacity-50"
                  >
                    <Sparkles size={14} />
                    <span>{activating ? 'Verifying...' : 'Activate Now'}</span>
                  </button>
                </div>

                {activationMsg && (
                  <div
                    className={`rounded-xl p-3 text-xs font-semibold flex items-center gap-2 ${
                      activationMsg.success
                        ? 'bg-emerald-50 text-emerald-800 border border-emerald-200'
                        : 'bg-rose-50 text-rose-800 border border-rose-200'
                    }`}
                  >
                    {activationMsg.success ? <CheckCircle2 size={16} /> : <ShieldAlert size={16} />}
                    <span>{activationMsg.text}</span>
                  </div>
                )}
              </form>
            ) : (
              <div className="rounded-xl border border-emerald-200 bg-emerald-50/70 p-3 text-xs text-emerald-900 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <CheckCircle2 size={16} className="text-emerald-600" />
                  <span className="font-semibold">
                    This installation is officially licensed to this computer. Unlimited scraping & CRM rights active.
                  </span>
                </div>
                <span className="text-[11px] font-mono font-bold text-emerald-700">{license?.license_key}</span>
              </div>
            )}
          </section>

          {/* 2. AGENCY WHITE-LABELING SECTION */}
          <section className="rounded-2xl border border-line bg-white p-6 shadow-xs space-y-4">
            <div className="flex items-center gap-2.5 border-b border-line pb-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-600 text-white shadow-md shadow-indigo-600/20">
                <Building2 size={20} />
              </div>
              <div>
                <h3 className="text-base font-bold text-ink">Agency White-Labeling & Branding</h3>
                <p className="text-xs text-muted">
                  Customize the software brand name, support phone, and client audit headers.
                </p>
              </div>
            </div>

            <form onSubmit={handleSaveBranding} className="grid gap-4 sm:grid-cols-2 text-xs">
              <div>
                <label className="text-[11px] font-bold uppercase tracking-wider text-slate-600 block mb-1">
                  Agency / Brand Name
                </label>
                <input
                  type="text"
                  value={branding.agency_name}
                  onChange={(e) => setBranding({ ...branding, agency_name: e.target.value })}
                  className="w-full rounded-xl border border-line bg-slate-50/60 p-2.5 font-semibold text-slate-900 outline-none focus:border-blue focus:bg-white"
                />
              </div>

              <div>
                <label className="text-[11px] font-bold uppercase tracking-wider text-slate-600 block mb-1">
                  Support WhatsApp / Phone
                </label>
                <input
                  type="text"
                  value={branding.support_phone}
                  onChange={(e) => setBranding({ ...branding, support_phone: e.target.value })}
                  className="w-full rounded-xl border border-line bg-slate-50/60 p-2.5 font-semibold text-slate-900 outline-none focus:border-blue focus:bg-white"
                />
              </div>

              <div>
                <label className="text-[11px] font-bold uppercase tracking-wider text-slate-600 block mb-1">
                  Support Email
                </label>
                <input
                  type="email"
                  value={branding.support_email}
                  onChange={(e) => setBranding({ ...branding, support_email: e.target.value })}
                  className="w-full rounded-xl border border-line bg-slate-50/60 p-2.5 font-semibold text-slate-900 outline-none focus:border-blue focus:bg-white"
                />
              </div>

              <div>
                <label className="text-[11px] font-bold uppercase tracking-wider text-slate-600 block mb-1">
                  Tagline / Edition
                </label>
                <input
                  type="text"
                  value={branding.tagline}
                  onChange={(e) => setBranding({ ...branding, tagline: e.target.value })}
                  className="w-full rounded-xl border border-line bg-slate-50/60 p-2.5 font-semibold text-slate-900 outline-none focus:border-blue focus:bg-white"
                />
              </div>

              <div className="sm:col-span-2 flex items-center justify-between pt-2">
                <span className="text-[11px] text-muted">
                  These details will appear in the Audit Proposals, Exports, and Outreach messages.
                </span>
                <button
                  type="submit"
                  disabled={savingBranding}
                  className="inline-flex items-center gap-1.5 rounded-xl bg-ink px-5 py-2.5 text-xs font-bold text-white hover:bg-slate-800 transition shadow-sm"
                >
                  {brandingSaved ? <Check size={14} className="text-emerald-400" /> : <Save size={14} />}
                  <span>{brandingSaved ? 'Saved Successfully!' : 'Save Branding'}</span>
                </button>
              </div>
            </form>
          </section>

          {/* 3. DATA SOURCE CONNECTORS */}
          <section className="rounded-2xl border border-line bg-white p-6 shadow-xs space-y-4">
            <div className="flex items-center gap-2 text-sm font-bold text-ink border-b border-line pb-3">
              <Server size={18} className="text-blue" />
              <span>Active Data Source Connectors</span>
            </div>

            <div className="space-y-3 pt-1">
              <div className="rounded-xl border border-emerald-200 bg-emerald-50/40 p-4 text-xs">
                <div className="flex items-center justify-between font-bold text-ink mb-1">
                  <span>Google Maps Direct (Live Places)</span>
                  <span className="text-emerald-700 font-bold bg-emerald-100 px-2 py-0.5 rounded-full text-[10px]">
                    Active • Zero API Cost
                  </span>
                </div>
                <p className="text-slate-600">
                  Direct local business discovery for all 38 Tamil Nadu districts. Extracts ratings, reviews, addresses, and phone numbers.
                </p>
              </div>

              <div className="rounded-xl border border-line bg-slate-50 p-4 text-xs">
                <div className="flex items-center justify-between font-bold text-ink mb-1">
                  <span>OpenStreetMap Overpass API (Tamil Nadu)</span>
                  <span className="text-emerald-600 font-semibold text-[10px]">Active</span>
                </div>
                <p className="text-slate-600">
                  Extracts commercial establishments with contact tags across Tamil Nadu under ODbL terms.
                </p>
              </div>

              <div className="rounded-xl border border-line bg-slate-50 p-4 text-xs">
                <div className="flex items-center justify-between font-bold text-ink mb-1">
                  <span>Google Places API (Cloud Key)</span>
                  <span className="text-slate-500 font-semibold text-[10px]">Optional</span>
                </div>
                <p className="text-slate-500 text-[11px]">
                  Configurable in backend environment file if official Google Cloud enterprise quotas are desired.
                </p>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
